id: FalconX - Test-Detonate URL
version: -1
name: FalconX - Test-Detonate URL
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4c8ad218-7568-4792-8e52-bc5421bebb4b
    type: start
    task:
      id: 4c8ad218-7568-4792-8e52-bc5421bebb4b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 7bee7513-f3cf-4dca-8bd8-26cecec90bcf
    type: regular
    task:
      id: 7bee7513-f3cf-4dca-8bd8-26cecec90bcf
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
      keysToKeep: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 388c23ee-ab6f-4ea7-8af6-70302f35822f
    type: regular
    task:
      id: 388c23ee-ab6f-4ea7-8af6-70302f35822f
      version: -1
      name: Set URL
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      append: {}
      key:
        simple: URL.Data
      value:
        simple: https://www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a19f504f-57d7-467a-807e-54d194efc612
    type: playbook
    task:
      id: a19f504f-57d7-467a-807e-54d194efc612
      version: -1
      name: FalconX - Detonate URL
      playbookName: FalconX - Detonate URL
      type: playbook
      iscommand: false
      brand: ""
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 620,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: Test-Detonate URL - Crowdstrike
